### ISSUE TITLE
ModularClocks scaling wrong

### ISSUE THREAD

**Issue by HeyitzGianny** [EnhancedJax/-JaxCore#11]
Hey,

while playing around with ModularClocks, I saw that if you use "2" in skin scaling, the 4th Clockstyle (the one, which lets you see time, temperature and date) isnt centered anymore and can't be drag & dropped anywhere on the bottom half of the screen (Monitor-Resolution : 2650x1440 , if it can be of any use..)

With Skin Scaling 2
![image](https://user-images.githubusercontent.com/76161140/141459538-359174b1-c3b9-4d1a-8598-fe6fabf64dae.png)

With skin Scaling 1
![image](https://user-images.githubusercontent.com/76161140/141459622-3f50e712-fd2a-49aa-ab85-c5b9feb0d86d.png)

Im running on Win11, might as well be the buggy hell of a system by microsoft

**Comment by EnhancedJax** [comment]
Thanks for reporting. I'll fix this soon!

**Comment by EnhancedJax** [comment]
Fixed with the newest release!
