### ISSUE TITLE
What is this?)

### ISSUE THREAD

**Issue by japanese-xevvo** [EnhancedJax/-JaxCore#13]
![image](https://user-images.githubusercontent.com/77848119/147761102-f1fb9987-fb12-49bd-8204-27010da311bc.png)
https://www.virustotal.com/gui/file/e4814bac41a57772534536f484bf0d527a555a3c22b53f70c92e35ca664f1cfb
https://virusscan.jotti.org/en-US/filescanjob/ohm2go9d8e

**Comment by EnhancedJax** [comment]
That's the executable used to select colours. .rmskin files are known to return false positives for Victoria checks. You can view the source code in this repo.
